apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DB_HOST: {{ .Values.backend.config.dbHost | quote }}
  DB_PORT: {{ .Values.backend.config.dbPort | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.backend.config.corsAllowedOrigins | quote }}