{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: 8080
      path: /actuator/prometheus
      interval: 45s
{{- end}}